// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UltimateRedditBot.Discord.Database;

namespace UltimateRedditBot.Migrations.Migrations.UltimateDiscordDb
{
    [DbContext(typeof(UltimateDiscordDbContext))]
    [Migration("20210213105040_BannedSubreddits")]
    partial class BannedSubreddits
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("UltimateRedditBot.Discord.Domain.Models.BannedSubreddit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<decimal?>("GuildId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("SubredditId")
                        .HasColumnType("int");

                    b.Property<decimal?>("UserId")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("UserId");

                    b.ToTable("BannedSubreddits");
                });

            modelBuilder.Entity("UltimateRedditBot.Discord.Domain.Models.DiscordChannel", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

                    b.Property<decimal>("GuildId")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("DiscordChannels");
                });

            modelBuilder.Entity("UltimateRedditBot.Discord.Domain.Models.Guild", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

                    b.Property<DateTime>("CreatedAtUTC")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAtUTC")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("UltimateRedditBot.Discord.Domain.Models.GuildSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreatedAtUTC")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("Prefix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAtUTC")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("GuildSettings");
                });

            modelBuilder.Entity("UltimateRedditBot.Discord.Domain.Models.PostHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<decimal?>("GuildId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("PostId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubredditId")
                        .HasColumnType("int");

                    b.Property<decimal?>("UserId")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("UserId");

                    b.ToTable("PostHistories");
                });

            modelBuilder.Entity("UltimateRedditBot.Discord.Domain.Models.User", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

                    b.Property<DateTime>("CreatedAtUTC")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAtUTC")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UltimateRedditBot.Discord.Domain.Models.UserSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Prefix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UserId")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("UltimateRedditBot.Discord.Domain.Models.BannedSubreddit", b =>
                {
                    b.HasOne("UltimateRedditBot.Discord.Domain.Models.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId");

                    b.HasOne("UltimateRedditBot.Discord.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Guild");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UltimateRedditBot.Discord.Domain.Models.DiscordChannel", b =>
                {
                    b.HasOne("UltimateRedditBot.Discord.Domain.Models.Guild", "Guild")
                        .WithMany("Channels")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("UltimateRedditBot.Discord.Domain.Models.GuildSettings", b =>
                {
                    b.HasOne("UltimateRedditBot.Discord.Domain.Models.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("UltimateRedditBot.Discord.Domain.Models.PostHistory", b =>
                {
                    b.HasOne("UltimateRedditBot.Discord.Domain.Models.Guild", null)
                        .WithMany("PostHistories")
                        .HasForeignKey("GuildId");

                    b.HasOne("UltimateRedditBot.Discord.Domain.Models.User", null)
                        .WithMany("PostHistories")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("UltimateRedditBot.Discord.Domain.Models.UserSettings", b =>
                {
                    b.HasOne("UltimateRedditBot.Discord.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UltimateRedditBot.Discord.Domain.Models.Guild", b =>
                {
                    b.Navigation("Channels");

                    b.Navigation("PostHistories");
                });

            modelBuilder.Entity("UltimateRedditBot.Discord.Domain.Models.User", b =>
                {
                    b.Navigation("PostHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
