// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UltimateRedditBot.Database;

namespace UltimateRedditBot.Migrations.Migrations
{
    [DbContext(typeof(UltimateDbContext))]
    [Migration("20210227161442_Subscriptions_Post_Re_Add_PostId")]
    partial class Subscriptions_Post_Re_Add_PostId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "6.0.0-preview.1.21102.2")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UltimateRedditBot.Domain.Models.Reddit.Post", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUTC")
                        .HasColumnType("datetime2");

                    b.Property<int>("Downs")
                        .HasColumnType("int");

                    b.Property<bool>("IsOver18")
                        .HasColumnType("bit");

                    b.Property<string>("PostLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostType")
                        .HasColumnType("int");

                    b.Property<string>("Selftext")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubRedditId")
                        .HasColumnType("int");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAtUTC")
                        .HasColumnType("datetime2");

                    b.Property<int>("Ups")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SubRedditId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("UltimateRedditBot.Domain.Models.Reddit.Subreddit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAtUTC")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsNsfw")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAtUTC")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Subreddits");
                });

            modelBuilder.Entity("UltimateRedditBot.Domain.Models.Reddit.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PostId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<int>("SubredditId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("SubredditId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("UltimateRedditBot.Domain.Models.Settings.GenericSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeyGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GenericSettings");
                });

            modelBuilder.Entity("UltimateRedditBot.Domain.Models.Reddit.Post", b =>
                {
                    b.HasOne("UltimateRedditBot.Domain.Models.Reddit.Subreddit", "Subreddit")
                        .WithMany("Posts")
                        .HasForeignKey("SubRedditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subreddit");
                });

            modelBuilder.Entity("UltimateRedditBot.Domain.Models.Reddit.Subscription", b =>
                {
                    b.HasOne("UltimateRedditBot.Domain.Models.Reddit.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId");

                    b.HasOne("UltimateRedditBot.Domain.Models.Reddit.Subreddit", "Subreddit")
                        .WithMany()
                        .HasForeignKey("SubredditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Subreddit");
                });

            modelBuilder.Entity("UltimateRedditBot.Domain.Models.Reddit.Subreddit", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
